Require enum-ordinalise 4.2.1
4.2.0 does not build, because num-bigint doesn't:

   Compiling num-bigint v0.4.0
error[E0308]: mismatched types
  --> /home/rustcargo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.0/src/biguint/convert.rs:70:19
   |
70 |         .div_ceil(&big_digit::BITS.into())
   |          -------- ^^^^^^^^^^^^^^^^^^^^^^^ expected `u64`, found `&_`
   |          |
   |          arguments to this method are incorrect
   |
   = note:   expected type `u64`
           found reference `&_`